####
## Boseji's GIT Config
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####
[user]
  name = boseji
  email = boseji@users.noreply.github.com
  tag = boseji
[color]
  diff = auto
  status = auto
  branch = auto
  interactive = auto
  ui = auto
[color "branch"]
  current = green bold
  local = green
  remote = red bold  
[color "diff"]
  meta = yellow bold
  frag = magenta bold
  old = red bold
  new = green bold
[color "status"]
  added = green bold
  changed = yellow bold
  untracked = red
[color "sh"]
  branch = yellow
[push]
  # 'git push' should only do the current branch, not all
  default = current
[branch]
  # always setup 'git pull' to rebase instead of merge
  autosetuprebase = always
# Special inclusion for the `go get` commands targeted to own repos
[url "git@github.com:boseji/"]
	insteadOf = https://github.com/boseji/
[alias]
  	st = status
	ci = commit
	br = branch
	cl = clone --recursive
	co = checkout
	df = diff
	pl = pull --all
	ds = diff --staged
	lg = log -p
	lol = log --graph --decorate --pretty=oneline --abbrev-commit
	lola = log --graph --decorate --pretty=oneline --abbrev-commit --all --date=local
	ls = ls-files
	unstage = reset HEAD
	#additional Short cuts
	y = diff "@{yesterday}"
	w = whatchanged
	dc = diff --cached
	# Show files ignored by git:
	ign = ls-files -o -i --exclude-standard
	# Fancy Logging
	lgl = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative
	lgn = "!f() { git log --graph --pretty=format:'%Cred%H%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --date=relative $@ | git name-rev --stdin --name-only ; } ; f"
	log1 = log --pretty=oneline --abbrev-commit --decorate

