#!/bin/bash
#                                                          -*- shell-script -*-
#

####
##
## Boseji's SAM Microcntroller Programmer Install Script
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

export package=bossa
export packageurl=https://aur.archlinux.org/bossa.git
export packagestr="bossac for Microchip SAM"

./install-from-aur $package $packageurl $packagestr

