#!/bin/bash
#                                                          -*- shell-script -*-
#

####
##
## Boseji's Custom Package installation for Manjaro / Arch Linux
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

# Exit On Error
set -e

# Update Repos - with upgrade
sudo pacman -Syu

# Packages - System
sudo pacman -S htop tree lbzip2 hddtemp lm_sensors \
	virtualbox linux54-virtualbox-host-modules virtualbox-guest-iso \
	bash-completion docker tmux arch-audit fakeroot patch grsync

# Packages - Security
sudo pacman -S keepassxc veracrypt libgcrypt

# Packages - Development
sudo pacman -S make cmake code gitg \
	python-pip python-virtualenv python-pygments \
	go nodejs npm nano-syntax-highlighting \
	rustup lldb gdb

# Packages - Docs
sudo pacman -S pdftk pdfarranger zbar \
	ttf-roboto ttf-roboto-mono gnu-free-fonts \
	ttf-material-icons

# Packages - Embedded
sudo pacman -S moserial lrzsz picocom stlink python-pyserial

# Packages - Internet Communications
sudo pacman -S chromium telegram-desktop ttf-opensans

# Packages - Multimedia
sudo pacman -S vlc
sudo -H pip install --upgrade youtube-dl

# Packages - Extras
# sudo pacman -S xfce4-sensors-plugin

