#!/bin/bash
#                                                          -*- shell-script -*-
#

####
##
## Boseji's Arch / Manjaro Linux user Profile Creation Script
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

# Get Current Directory
export CPWD="$(pwd)"

# Make sure we are in correct directory
export pDIR="$(cd "$(dirname "$0")" && pwd)"
cd $pDIR

# Print Usage
if [ "$1" == "-h" -o "$1" == "--help" ] ; then
echo
echo " Boseji's Arch / Manjaro Linux user Profile Creation Script"
echo
echo " Usage:"
echo "   $  ./install-profile [-f]"
echo
echo " Where:"
echo "   -f (optional) This flag can force over-writing the profile files."
echo "         Means the install would overwrite '.bashrc', '.bash_profile'"
echo "         '.profile' and '.dir_colors' files in User Home directory."
echo
fi

export ubuntu="$(cat /etc/issue | grep Ubuntu)"
export manjaro="$(cat /etc/issue | grep Manjaro)"
export arch="$(cat /etc/issue | grep Arch)"

if [ ! -z "$manjaro" ] ; then

    echo
    echo "Manjaro OS found"
    echo
    if [ "$1" == "-f" ]; then
        echo "   Copying files .profile files"
        echo
        /bin/cp -v -- ./originals-manjaro/.* $HOME
    fi

elif [ ! -z "$ubuntu" ] ; then

    echo
    echo "Ubuntu OS found"
    echo
    if [ "$1" == "-f" ]; then
        echo "   Copying files"
        echo
        /bin/cp -v -- ./originals-ubuntu/.* $HOME
    fi
elif [ ! -z "$arch" ] ; then

    echo
    echo "ARCH Linux OS found"
    echo
    if [ "$1" == "-f" ]; then
        echo "   Copying files .profile files"
        echo
        /bin/cp -v -- ./originals-manjaro/.* $HOME
    fi
else
    
    echo
    echo " Un-known Linux Distro "
    echo
    exit 1

fi

echo
echo "   Copying other profile files"
echo
# Copy Files
/bin/cp -v ./bash.aliases.sh $HOME/bash.aliases
/bin/cp -v ./bash.exports.sh $HOME/bash.exports
/bin/cp -v ./gitconfig.toml $HOME/.gitconfig
/bin/cp -v ./tmux.conf.sh $HOME/.tmux.conf
/bin/cp -v ./hyper.js $HOME/.hyper.js
/bin/cp -v ./nanorc.sh $HOME/.nanorc

# Funciton to add files to .rsyncignore
rsynci() 
{
    local fl=$1
    # Create the file if it does not exist
    if [[ ! -e "$HOME/.rsyncignore" ]] ; then
        echo
        echo "   Created Rsync Ignore File"
        echo
        touch $HOME/.rsyncignore
    fi
    if [[ -z "$(cat $HOME/.rsyncignore | grep ${fl})" ]] ; then
        echo
        echo "   Rsync Ignore configured for ${fl}"
        echo
        echo "${fl}" >> $HOME/.rsyncignore
    fi
}
# Add ignore for the files not needing backup
#rsynci bash.aliases
#rsynci bash.exports
#rsynci .gitconfig
#rsynci .tmux.conf
#rsynci .hyper.js
#rsynci .nanorc

echo
echo "   Running the Bin directory Installation"
echo
# Run Other installs
bash ./install-bin

# Bashrc customization
export custom="$(cat $HOME/.bashrc | grep Boseji)"
if [ -z "$custom" ] ; then
echo
echo "   Perform .bashrc customization"
echo

echo '

####
## Boseji s Bash Customization
####
[[ -e "$HOME/bash.aliases" ]] && source $HOME/bash.aliases
[[ -e "$HOME/bash.exports" ]] && source $HOME/bash.exports
[[ -e "$HOME/bash_aliases" ]] && source $HOME/bash_aliases
[[ -e "$HOME/bash_exports" ]] && source $HOME/bash_exports
[[ -e "$HOME/digitalocean.env" ]] && source $HOME/digitalocean.env

' >> $HOME/.bashrc
fi

# Golang Directory Fix
if [[ ! -d "$HOME/go/src" ]] ; then
    echo
    echo "   Adding Golang directories"
    echo
    mkdir -p $HOME/go/src $HOME/go/bin
    echo
    tree $HOME/go
fi

# Done
cd $CPWD

echo
echo " Done...!"
echo
