#!/bin/bash
#                                                          -*- shell-script -*-
#

####
##
## Boseji's Arch / Manjaro Linux user Profile Creation Script
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

# Get Current Directory
export CPWD="$(pwd)"

# Make sure we are in correct directory
export pDIR="$(cd "$(dirname "$0")" && pwd)"
cd $pDIR

export ubuntu="$(cat /etc/issue | grep Ubuntu)"
export manjaro="$(cat /etc/issue | grep Manjaro)"

if [ ! -z "$manjaro" ] ; then

    echo
    echo "Manjaro OS found"
    echo
    if [ "$1" == "-f" ]; then
        echo "   Copying files .profile files"
        echo
        /bin/cp -v -- ./originals-manjaro/.* $HOME
    fi

elif [ ! -z "$ubuntu" ] ; then

    echo
    echo "Ubuntu OS found"
    echo
    if [ "$1" == "-f" ]; then
        echo "   Copying files"
        echo
        /bin/cp -v -- ./originals-ubuntu/.* $HOME
    fi

else
    
    echo
    echo " Un-known Linux Distro "
    echo
    exit 1

fi

echo
echo "   Copying other profile files"
echo
# Copy Files
/bin/cp -v ./bash.aliases.sh $HOME/bash.aliases
/bin/cp -v ./bash.exports.sh $HOME/bash.exports
/bin/cp -v ./gitconfig.toml $HOME/.gitconfig
/bin/cp -v ./tmux.conf.sh $HOME/.tmux.conf
/bin/cp -v ./hyper.js $HOME/.hyper.js

# Funciton to add files to .rsyncignore
rsynci() 
{
    local fl=$1
    if [[ -z "$(cat $HOME/.rsyncignore | grep ${fl})" ]] ; then
        echo "${fl}" >> $HOME/.rsyncignore
    fi
}

rsynci bash.aliases
rsynci bash.exports
rsynci .gitconfig
rsynci .tmux.conf
rsynci .hyper.js

echo
echo "   Running the Bin directory Installation"
echo
# Run Other installs
bash ./install-bin

# Bashrc customization
export custom="$(cat $HOME/.bashrc | grep Boseji)"
if [ -z "$custom" ] ; then
echo
echo "   Perform .bashrc customization"
echo

echo '

####
## Boseji s Bash Customization
####
[[ -e "$HOME/bash.aliases" ]] && source $HOME/bash.aliases
[[ -e "$HOME/bash.exports" ]] && source $HOME/bash.exports

' >> $HOME/.bashrc
fi

# Golang Directory Fix
if [[ ! -d "$HOME/go/src" ]] ; then
    echo
    echo "   Adding Golang directories"
    echo
    mkdir -p $HOME/go/src $HOME/go/bin
    echo
    tree $HOME/go
fi

# Update the Current Profile
[[ -e "$HOME/.profile" ]] && source $HOME/.profile 
[[ -e "$HOME/.bash_profile" ]] && source $HOME/.bash_profile

# Done
cd $CPWD

echo
echo " Done...!"
echo