#!/bin/bash
#                                                          -*- shell-script -*-
#

echo "
####
##
## Boseji's Custom Package installation for Manjaro / Arch Linux
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

"
# Exit On Error
set -e

echo " - Update Repos - with upgrade"
echo
sudo pacman -Syu
echo
echo " - Installing Packages - System"
echo
sudo pacman -S htop tree lbzip2 hddtemp lm_sensors stow \
	bash-completion docker tmux arch-audit fakeroot patch \
	grsync smartmontools
echo	
echo " - Add user to the Required Groups"
sudo usermod -aG uucp $USER
sudo usermod -aG lock $USER
sudo usermod -aG docker $USER
echo
echo " - Installing Packages - Security"
echo
sudo pacman -S keepassxc veracrypt libgcrypt
echo
echo " - Installing Packages - Development"
echo
sudo pacman -S make cmake code gitg \
	python-pip python-virtualenv python-pygments \
	go nodejs npm nano-syntax-highlighting \
	rustup lldb gdb meld
echo
echo " - Installing Packages - Documents and Spell Checkers"
echo
sudo pacman -S pdftk pdfarranger zbar \
	ttf-roboto ttf-roboto-mono gnu-free-fonts \
	ttf-jetbrains-mono ttf-ionicons ttf-font-icons ttf-font-awesome \
	ttf-fira-mono ttf-fira-sans ttf-fira-code ttf-comfortaa \
	ttf-cormorant ttf-croscore ttf-carlito ttf-bitstream-vera \
	ttf-indic-otf ttf-inconsolata ttf-droid noto-fonts \
	hunspell-en_US hyphen-en libmythes mythes-en
echo
echo " - Installing Packages - Embedded & Electronics"
sudo pacman -S openocd moserial lrzsz picocom stlink python-pyserial
echo
echo " - Installing Packages - Internet Communications"
sudo pacman -S telegram-desktop ttf-opensans
echo
echo " - Installing Packages - Multimedia Tools"
echo
sudo pacman -S vlc audacity simplescreenrecorder youtube-dl
echo
# Packages - Extras
# sudo pacman -S xfce4-sensors-plugin
# Download MPLABX-Installer for Linux
# wget -c https://www.microchip.com/mplabx-ide-linux-installer -O mplabx-ide-linux-installer.tar
# tar -xf mplabx-ide-linux-installer.tar
# sudo sh ./MPLABX-*-installer.sh
# wget -c https://www.microchip.com/mplabxc8linux -O mplabx-xc8-installer.run
# chmod +x mplabx-xc8-installer.run
# sudo ./mplabx-xc8-installer.run
