#!/bin/bash
#                                                          -*- shell-script -*-
#

####
##
## Boseji's HUGO static website generator Install Script
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

URL="https://api.github.com/repos/gohugoio/hugo/releases/latest"
FILECHAR="hugo_extended_*_Linux-64bit.tar.gz"
PATTERN="extended.*_Linux-64bit.tar.gz"
PROGRAM="hugo"

./install-from-github $URL $FILECHAR $PATTERN $PROGRAM