#!/bin/bash
#                                                          -*- shell-script -*-
#

####
##
## Boseji's Home Bin Directory Configuration Script
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

if [[ ! -d "$HOME/bin" ]] ; then
    mkdir -p $HOME/bin
fi

cp -r ./bin $HOME
