#!/bin/bash
#                                                          -*- shell-script -*-
#

####
##
## Boseji's Home Bin Directory Configuration Script
##
## SPDX-License-Identifier: GPL-2.0-only
##
## Copyright (C) 2020 Abhijit Bose <boseji@users.noreply.github.com>
##
####

if [[ ! -d "$HOME/bin" ]] ; then
	echo
	echo "    Creating Bin directory in HOME"
	echo
    mkdir -p $HOME/bin
fi

cp -v -r ./bin $HOME

ls -1 ./bin > $HOME/bin/.rsyncignore
